version: '3'

services:
    camunda:
        image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:${DISTRO:-7.16.0}
        environment:
            - DB_DRIVER=org.postgresql.Driver
            - DB_URL=jdbc:postgresql://db:5433/camunda
            - DB_USERNAME=camunda
            - DB_PASSWORD=camunda
            - WAIT_FOR=db:5433
        links:
            - db
        depends_on:
            - db
        ports:
            - "9080:8080"
        restart: unless-stopped

    db:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=camunda
            - POSTGRES_PASSWORD=camunda
        expose:
            - "5433"
        ports:
            - "5433:5432"
